import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import LayoutController from "@/components/layoutController";
import ReduxWrapper from "@/components/reduxWrapper";

const montserral = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserral.className}>
        <ReduxWrapper>
          <LayoutController>
            <>
              {children}
            </>
          </LayoutController>
        </ReduxWrapper>
      </body>
    </html>
  );
}
